---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://api.netlify.com/build_hooks/6078407a8d9ebb0c730b273d
sections:
- type: heading
  label: Innehåll
- type: directory
  path: content/posts
  label: Inlägg
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: content/pages
  label: Sidor
  create: documents
  match: "**/*"
  templates:
  - pages
- type: heading
  label: Information
- type: document
  path: config.json
  label: Allmänt
- type: document
  path: content/data/author.json
  label: Om författaren
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
